[GraphControll]
refresh = 0.1
utf8 = True

[Temp,Graphs]
acpitz,0 = True
packageid0,0 = True
core0,0 = True
core1,0 = True
core2,0 = True
core3,0 = True
core4,0 = True
core5,0 = True
iwlwifi_1,0 = False
jc42,0 = False
jc42,1 = False
composite,0 = False
composite,1 = False
sensor1,0 = False
sensor2,0 = True
pch_cometlake,0 = True

[Frequency,Graphs]
avg = True
core 0 = True
core 1 = True
core 2 = True
core 3 = True
core 4 = True
core 5 = True
core 6 = True
core 7 = True
core 8 = True
core 9 = True
core 10 = True
core 11 = True

[Util,Graphs]
avg = True
core 0 = True
core 1 = True
core 2 = True
core 3 = True
core 4 = True
core 5 = True
core 6 = True
core 7 = True
core 8 = True
core 9 = True
core 10 = True
core 11 = True

[Power,Graphs]

[Temp,Summaries]
acpitz,0 = True
packageid0,0 = True
core0,0 = True
core1,0 = True
core2,0 = True
core3,0 = True
core4,0 = True
core5,0 = True
iwlwifi_1,0 = False
jc42,0 = False
jc42,1 = False
composite,0 = False
composite,1 = False
sensor1,0 = False
sensor2,0 = True
pch_cometlake,0 = True

[Frequency,Summaries]
avg = True
core 0 = True
core 1 = True
core 2 = True
core 3 = True
core 4 = True
core 5 = True
core 6 = True
core 7 = True
core 8 = True
core 9 = True
core 10 = True
core 11 = True

[Util,Summaries]
avg = True
core 0 = True
core 1 = True
core 2 = True
core 3 = True
core 4 = True
core 5 = True
core 6 = True
core 7 = True
core 8 = True
core 9 = True
core 10 = True
core 11 = True

[Power,Summaries]

