# Fixes a bug where Discord notifications are silent if min.quantum is too low.

pulse.rules = [
    {
        matches = [
            {
                application.process.binary = "Discord"
            }
        ]
        actions = {
            update-props = {
                pulse.min.quantum = 1024/48000 # 21 ms
            }
        }
    }
]
