#!/bin/sh

# Config editing helpers
alias edit-env="$EDITOR $XDG_CONFIG_HOME/shell/env"
alias edit-xinitrc="$EDITOR $XDG_CONFIG_HOME/X11/.xinitrc"
alias edit-xresources="$EDITOR $XDG_CONFIG_HOME/X11/.Xresources"
alias edit-xmodmap="$EDITOR $XDG_CONFIG_HOME/X11/.Xmodmap"
alias edit-profile="$EDITOR $XDG_CONFIG_HOME/shell/profile"
alias edit-aliases="$EDITOR $XDG_CONFIG_HOME/shell/aliases"
alias edit-keybinds="$EDITOR $XDG_CONFIG_HOME/sxhkd/sxhkdrc"
alias edit-bashrc="$EDITOR $XDG_CONFIG_HOME/bash/.bashrc"
alias edit-zshrc="$EDITOR $ZDOTDIR/.zshrc"

# System helpers
alias update-initramfs='sudo mkinitcpio -P'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias update-xresources="xrdb -remove * && xrdb -load $HOME/.Xresources"

# Dotfile repo helpers
alias dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias dotfiles-list='dotfiles ls-tree -r main --name-only'

# Pass aliases thru sudo
alias sudo='sudo '

# Format a C/C++ file
alias cformat='clang-format --style=file'

# Open IDA Free
alias ida="($XDG_DATA_HOME/idafree-8.3/ida64 &)"

# Colored command output
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'

# XDG compliance shims
alias wget="wget --hsts-file=$XDG_DATA_HOME/wget-hsts"

# Fancy LS
alias l='eza'
alias ll='eza --long'
alias la='eza --all'
alias lla='eza --long --all'
alias eza='eza					\
	--sort=name                 \
	--icons=always				\
	--smart-group				\
	--octal-permissions			\
	--group-directories-first'

# Command shortcuts
alias nv='nvim'
alias calc='qalc'
alias todo='task'
alias fetch='fastfetch'
alias iftop='sudo iftop -i wlp8s0'
alias matrix='cmatrix -abs -u 2 -C green'
alias aquarium='asciiquarium'
alias bonsai='cbonsai -li'
alias art='arttime'
alias moon='phoon'
alias weather="curl --silent https://wttr.in/brisbane | sed -E 's/(Follow.*|Weather report.*)//g'"
