#!/bin/sh

alias edit-env="$EDITOR $XDG_CONFIG_HOME/shell/env"
alias edit-xinitrc="$EDITOR $XDG_CONFIG_HOME/X11/.xinitrc"
alias edit-xresources="$EDITOR $XDG_CONFIG_HOME/X11/.Xresources"
alias edit-xmodmap="$EDITOR $XDG_CONFIG_HOME/X11/.Xmodmap"
alias edit-profile="$EDITOR $XDG_CONFIG_HOME/shell/profile"
alias edit-aliases="$EDITOR $XDG_CONFIG_HOME/shell/aliases"
alias edit-keybinds="$EDITOR $XDG_CONFIG_HOME/sxhkd/sxhkdrc"
alias edit-bashrc="$EDITOR $XDG_CONFIG_HOME/bash/.bashrc"
alias edit-zshrc="$EDITOR $ZDOTDIR/.zshrc"

alias update-initramfs='sudo mkinitcpio -P'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'

alias dotfiles="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
alias dotfiles-list='dotfiles ls-tree -r main --name-only'

alias sudo='sudo '

alias n='(alacritty --working-directory $(pwd) &); disown -a'

alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'

alias eza='eza					\
	--sort=name                 \
	--icons=always				\
	--smart-group				\
	--octal-permissions			\
	--group-directories-first'

alias l='eza'
alias ll='eza --long'
alias la='eza --all'
alias lla='eza --long --all'

alias nv='nvim'
alias calc='qalc'
alias todo='task'
alias tasks='task list'
alias matrix='cmatrix -abs -u 2 -C green'
alias aquarium='asciiquarium'
alias bonsai='cbonsai -li'
alias art='arttime'
alias fetch='fastfetch'
alias iftop='sudo iftop -i wlp8s0'
alias weather="curl --silent https://wttr.in/brisbane | sed -E 's/(Follow.*|Weather report.*)//g'"
alias moon='phoon'

# vim:set ts=4 sts=4 sw=4:
