# There is a bug in WirePlumber that causes some applications to trigger switching to the Headset Profile (HFP).
# This fixes the issue by completely disabling the switching and support for Headset Profile (HFP).
# This completely disables the headset's integrated microphone and improves the audio quality when using a microphone.

wireplumber.settings = {
    # Disable switching to the Headset Profile (HFP) when an input stream is present.
    bluetooth.autoswitch-to-headset-profile = false
}

monitor.bluez.properties = {
    # Currently some headsets (e.g., Sony WH-1000XM3) are not working when both hsp_ag and hfp_ag are enabled, so only
    # HFP will be enabled by default.
    #
    # Enabled roles (default: [ a2dp_sink a2dp_source bap_sink bap_source hfp_hf hfp_ag ])
    #
    # Supported roles: hsp_hs (HSP Headset)
    #                  hsp_ag (HSP Audio Gateway)
    #                  hfp_hf (HFP Hands-Free)
    #                  hfp_ag (HFP Audio Gateway)
    #                  a2dp_sink (A2DP Audio Sink)
    #                  a2dp_source (A2DP Audio Source)
    #                  bap_sink (LE Audio Basic Audio Profile Sink)
    #                  bap_source (LE Audio Basic Audio Profile Source)
    #
    # Only use A2DP to fix bluetooth issues.
    bluez5.roles = [ a2dp_sink a2dp_source ]
}
