# Prevent the microphone volume from automatically lowering while Vesktop is active.
# The binary name may vary depending on the version that is installed (e.g., electron).

access.rules = [
    {
        matches = [
            {
                application.process.binary = "vesktop"
            }
        ]
        actions = [
            update-props = {
                default_permissions = "rx"
            }
        ]
    }
]
